# Generated by Django 5.2.4 on 2025-07-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='time',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
    ]
