# Generated by Django 5.2.4 on 2025-07-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_fitnessclass_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
