# Generated by Django 5.2.4 on 2025-07-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_fitnessclass_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='capacity',
        ),
    ]
