# Generated by Django 5.2.4 on 2025-07-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_fitnessclass_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
