# Generated by Django 5.2.4 on 2025-07-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_reservation_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='feedback',
            field=models.TextField(blank=True),
        ),
    ]
