# Generated by Django 5.2.4 on 2025-07-13 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_reservation_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='score',
            new_name='rating',
        ),
    ]
