# Generated by Django 5.2.4 on 2025-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='class_type',
            field=models.CharField(choices=[('muscle_gain', 'Muscle Gain'), ('flexibility', 'Flexibility'), ('weight_loss', 'Weight Loss'), ('general_fitness', 'General Fitness')], default='weight_loss', max_length=20),
        ),
    ]
