# Generated by Django 5.2.4 on 2025-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_fitnessclass_class_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
