# Generated by Django 5.2.4 on 2025-07-20 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_fitnessclass_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_goal',
            field=models.CharField(choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('flexibility', 'Flexibility'), ('muscle_gain', 'Muscle Gain'), ('stress_relief', 'Stress Relief'), ('post_injury_reha', 'Post-injury Reha'), ('endurance_training', 'Endurance Training'), ('improve_sleep', 'Improve Sleep')], default='weight_loss', max_length=30),
        ),
    ]
