# Generated by Django 5.2.4 on 2025-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_userprofile_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_instructor',
            field=models.BooleanField(default=False),
        ),
    ]
