# Generated by Django 5.2.4 on 2025-07-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_userprofile_is_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='post_class_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
