# Generated by Django 5.2.4 on 2025-07-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_fitnessclass_post_class_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='intro_videos/'),
        ),
    ]
